spring.application.name=adk

# Expose the internal routing and tool execution of the Google ADK
logging.level.com.google.adk=DEBUG

logging.level.org.springframework.web=INFO
gemini.agent.model=gemini-2.5-flash-lite

# Reveal Feign Client HTTP calls
logging.level.com.learning.adk=DEBUG

# --- Feign Client Timeouts (in milliseconds) ---

# How long Feign should wait to establish the initial network connection
spring.cloud.openfeign.client.config.weatherClient.connectTimeout=10000

# How long Feign should wait for the actual data to arrive after connecting
spring.cloud.openfeign.client.config.weatherClient.readTimeout=20000